---
- name: Ensure nf_conntrack kernel module is loaded
  modprobe:
    name: nf_conntrack
    state: present

- name: Update sysctl net settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "fs.file-max", value: 65535 }
    - { name: "net.core.somaxconn", value: 4096 }
    - { name: "net.core.rmem_max", value: 16777216 }
    - { name: "net.core.wmem_max", value: 16777216 }
    - { name: "net.ipv4.ip_local_port_range", value: "10000 65535"}
    - { name: "net.netfilter.nf_conntrack_tcp_timeout_time_wait", value: "1"}
    - { name: "net.ipv4.tcp_rmem", value: "4096 87380 16777216" }
    - { name: "net.ipv4.tcp_wmem", value: "4096 16384 16777216" }
    - { name: "net.ipv4.tcp_fin_timeout", value: "15" }

- name: Update sysctl net settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "net.ipv4.tcp_tw_reuse", value: 1 }
  when: ansible_lsb.major_release|int < 18

- name: Update limits.conf limits
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
    state: present
    insertafter: EOF
    create: True
  with_items:
    - "* hard nofile 65535"
    - "* soft nofile 65535"
    - "* hard nproc 16384"
    - "* soft nproc 16384"

- name: Update sysctl.conf limits
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
    state: present
    insertafter: EOF
    create: True
  with_items:
    - "vm.swappiness = 0"
  when: linux_config_swap_off

- name: Set noatime for partitions by src
  mount:
    path: /
    src: "{{ item }}"
    fstype: ext4
    opts: rw,noatime
    state: mounted
  with_items:
    - linux_config_noatime_srcs
